## Demostracion de Pandas

In [108]:
lista = [0,1,2,3,4,5,6,7]

In [109]:
lista2 = ["Save","The","Pandas"]

In [110]:
lista[0]

0

In [111]:
lista[1:3]

[1, 2]

In [112]:
for number in lista:
    print number

0
1
2
3
4
5
6
7


In [113]:
for cadena in lista2:
    print cadena

Save
The
Pandas


In [114]:
lista2

['Save', 'The', 'Pandas']

In [115]:
len(lista2)

3

In [116]:
range(0,len(lista2))

[0, 1, 2]

In [117]:
for position in range(0,len(lista2)):
    print lista2[position]

Save
The
Pandas


In [118]:
for i, element in enumerate(lista2):
    print i
    print element

0
Save
1
The
2
Pandas


In [119]:
lista

[0, 1, 2, 3, 4, 5, 6, 7]

In [120]:
lista3 = [2*number+1 for number in lista]

In [121]:
lista

[0, 1, 2, 3, 4, 5, 6, 7]

In [122]:
lista3

[1, 3, 5, 7, 9, 11, 13, 15]

### Diccionario

In [123]:
dic = {  "hello": 1 , 3 : "guays"  }

In [124]:
dic[3]

'guays'

In [125]:
for key in dic:
    print key

3
hello


In [126]:
for key in dic:
    print dic[key]

guays
1


## Numpy

In [127]:
import numpy as np

In [128]:
lista5 = [1,2,3,4,5]

In [129]:
array1 = np.array(lista5)

In [130]:
array1+1

array([2, 3, 4, 5, 6])

In [131]:
array1

array([1, 2, 3, 4, 5])

In [132]:
array2 = np.array(lista5)

In [133]:
array1+array2

array([ 2,  4,  6,  8, 10])

In [134]:
%time print "hello"

hello
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 33.1 µs


In [135]:
listamillon = range(0,1000000)

In [136]:
%time newlist = [number+1  for number in listamillon ]

CPU times: user 80 ms, sys: 0 ns, total: 80 ms
Wall time: 161 ms


In [137]:
arraymillon = np.arange(1000000)

In [138]:
%time newarray = arraymillon+1

CPU times: user 4 ms, sys: 4 ms, total: 8 ms
Wall time: 10.1 ms


# Pandas Series !!!!!!!!!

In [139]:
import pandas as pd

In [140]:
from pandas import Series

In [141]:
lista2

['Save', 'The', 'Pandas']

In [142]:
serie1 = Series(lista2)

In [143]:
serie1

0      Save
1       The
2    Pandas
dtype: object

In [144]:
serie2 = Series(lista2,index=[5,6,7])

In [145]:
serie2

5      Save
6       The
7    Pandas
dtype: object

In [146]:
serie2.index

Int64Index([5, 6, 7], dtype='int64')

In [147]:
serie2.index.values

array([5, 6, 7])

In [148]:
serie2.values

array(['Save', 'The', 'Pandas'], dtype=object)

In [149]:
serie3 = Series(lista2,index=["element1","element2","element3"])

In [150]:
serie3

element1      Save
element2       The
element3    Pandas
dtype: object

In [151]:
lista3

[1, 3, 5, 7, 9, 11, 13, 15]

In [152]:
serie4 = Series(lista3)

In [153]:
serie4

0     1
1     3
2     5
3     7
4     9
5    11
6    13
7    15
dtype: int64

In [154]:
serie4+serie4

0     2
1     6
2    10
3    14
4    18
5    22
6    26
7    30
dtype: int64

In [155]:
serie5 = Series(lista3,index=[1,2,3,4,5,6,7,8])

In [156]:
serie4+serie5

0   NaN
1     4
2     8
3    12
4    16
5    20
6    24
7    28
8   NaN
dtype: float64

In [157]:
serie5 = Series(lista3,index=[1,2,7,10,5,6,7,8])

In [158]:
serie5

1      1
2      3
7      5
10     7
5      9
6     11
7     13
8     15
dtype: int64

In [159]:
serie5[7]

7     5
7    13
dtype: int64

In [160]:
serie5+serie4

0    NaN
1      4
2      8
3    NaN
4    NaN
5     20
6     24
7     20
7     28
8    NaN
10   NaN
dtype: float64

## Pandas DataFrame

In [161]:
from pandas import DataFrame

In [162]:
serie4

0     1
1     3
2     5
3     7
4     9
5    11
6    13
7    15
dtype: int64

In [163]:
serie6 = 2*serie4

In [164]:
serie6

0     2
1     6
2    10
3    14
4    18
5    22
6    26
7    30
dtype: int64

In [165]:
dataframe1= DataFrame([serie4,serie6])

In [166]:
dataframe1

0  1   2   3   4   5   6   7
0  1  3   5   7   9  11  13  15
1  2  6  10  14  18  22  26  30

In [167]:
dataframe1= DataFrame({'col1':serie4,'col2':serie6})

In [168]:
dataframe1

col1  col2
0     1     2
1     3     6
2     5    10
3     7    14
4     9    18
5    11    22
6    13    26
7    15    30

In [169]:
dataframe1.columns

Index([u'col1', u'col2'], dtype='object')

In [170]:
dataframe1.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7], dtype='int64')

In [171]:
dataframe1["col1"]

0     1
1     3
2     5
3     7
4     9
5    11
6    13
7    15
Name: col1, dtype: int64

In [172]:
dataframe1["col2"]

0     2
1     6
2    10
3    14
4    18
5    22
6    26
7    30
Name: col2, dtype: int64

In [173]:
dataframe2 = DataFrame({"col1":[1,2,3],
                       "col2":["Save","the","Pandas"]})

In [174]:
dataframe2

col1    col2
0     1    Save
1     2     the
2     3  Pandas

In [175]:
dataframe2["col2"]


0      Save
1       the
2    Pandas
Name: col2, dtype: object

In [176]:
dataframe2["col2"][0]

'Save'

In [177]:
dataframe1

col1  col2
0     1     2
1     3     6
2     5    10
3     7    14
4     9    18
5    11    22
6    13    26
7    15    30

In [178]:
dataframe1["col3"]=1

In [179]:
dataframe1

col1  col2  col3
0     1     2     1
1     3     6     1
2     5    10     1
3     7    14     1
4     9    18     1
5    11    22     1
6    13    26     1
7    15    30     1

In [180]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [181]:
dataframe1["col5"]=np.arange(8)

In [182]:
dataframe1

col1  col2  col3  col5
0     1     2     1     0
1     3     6     1     1
2     5    10     1     2
3     7    14     1     3
4     9    18     1     4
5    11    22     1     5
6    13    26     1     6
7    15    30     1     7

In [183]:
np.nan

nan

In [184]:
[1,2,3,np.nan]

[1, 2, 3, nan]

In [185]:
array100 = np.array([1,2,3,np.nan])

In [186]:
dataframe3 = DataFrame(array100)

In [187]:
dataframe3

0
0   1
1   2
2   3
3 NaN

In [188]:
dataframe3.dropna()

0
0  1
1  2
2  3

In [189]:
dataframe3.T

0  1  2   3
0  1  2  3 NaN

In [190]:
dataframe3[0][2]

3.0

In [191]:
dataframe3[0][2] = 6

In [192]:
dataframe3[0][2]

6.0

In [193]:
dataframe3

0
0   1
1   2
2   6
3 NaN

In [194]:
dataframe3.columns

Int64Index([0], dtype='int64')

In [195]:
dataframe3.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [196]:
dataframe1

col1  col2  col3  col5
0     1     2     1     0
1     3     6     1     1
2     5    10     1     2
3     7    14     1     3
4     9    18     1     4
5    11    22     1     5
6    13    26     1     6
7    15    30     1     7

In [197]:
indice = dataframe1.index 

In [198]:
indice

Int64Index([0, 1, 2, 3, 4, 5, 6, 7], dtype='int64')

In [199]:
indice.values

array([0, 1, 2, 3, 4, 5, 6, 7])

In [200]:
indice[5]

5

In [201]:
#Esto da error
#indice[5] = 6

In [202]:
indice

Int64Index([0, 1, 2, 3, 4, 5, 6, 7], dtype='int64')

In [203]:
2 in indice

True

In [204]:
20 in indice

False

In [205]:
20 in dataframe1.index

False

In [206]:
dataframe1

col1  col2  col3  col5
0     1     2     1     0
1     3     6     1     1
2     5    10     1     2
3     7    14     1     3
4     9    18     1     4
5    11    22     1     5
6    13    26     1     6
7    15    30     1     7

In [207]:
dataframe1

col1  col2  col3  col5
0     1     2     1     0
1     3     6     1     1
2     5    10     1     2
3     7    14     1     3
4     9    18     1     4
5    11    22     1     5
6    13    26     1     6
7    15    30     1     7

In [209]:
dataframe1.columns = ["Columna1","Columna2","Columna3","Columna4"]

In [210]:
dataframe1

Columna1  Columna2  Columna3  Columna4
0         1         2         1         0
1         3         6         1         1
2         5        10         1         2
3         7        14         1         3
4         9        18         1         4
5        11        22         1         5
6        13        26         1         6
7        15        30         1         7

In [211]:
#Esto falla
#dataframe1.columns = ["c1","c2","c3","c4","c5"]

In [212]:
dataframe1.reindex(columns=["Columna1","c2","c3","c4","c5"])

Columna1  c2  c3  c4  c5
0         1 NaN NaN NaN NaN
1         3 NaN NaN NaN NaN
2         5 NaN NaN NaN NaN
3         7 NaN NaN NaN NaN
4         9 NaN NaN NaN NaN
5        11 NaN NaN NaN NaN
6        13 NaN NaN NaN NaN
7        15 NaN NaN NaN NaN

In [213]:
dataframe1.T

0  1   2   3   4   5   6   7
Columna1  1  3   5   7   9  11  13  15
Columna2  2  6  10  14  18  22  26  30
Columna3  1  1   1   1   1   1   1   1
Columna4  0  1   2   3   4   5   6   7

In [214]:
dataframe1

Columna1  Columna2  Columna3  Columna4
0         1         2         1         0
1         3         6         1         1
2         5        10         1         2
3         7        14         1         3
4         9        18         1         4
5        11        22         1         5
6        13        26         1         6
7        15        30         1         7

In [215]:
dataframe1.reindex([2,3,4,20,22,23])

Columna1  Columna2  Columna3  Columna4
2          5        10         1         2
3          7        14         1         3
4          9        18         1         4
20       NaN       NaN       NaN       NaN
22       NaN       NaN       NaN       NaN
23       NaN       NaN       NaN       NaN

In [216]:
dataframe1["c6"]=5

In [217]:
dataframe1

Columna1  Columna2  Columna3  Columna4  c6
0         1         2         1         0   5
1         3         6         1         1   5
2         5        10         1         2   5
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5

In [218]:
pd.concat([dataframe1,dataframe1])

Columna1  Columna2  Columna3  Columna4  c6
0         1         2         1         0   5
1         3         6         1         1   5
2         5        10         1         2   5
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5
0         1         2         1         0   5
1         3         6         1         1   5
2         5        10         1         2   5
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5

In [219]:
dataframeconvacios=dataframe1.reindex(columns=["Columna1","c2","c3"])

In [220]:
dataframeconvacios

Columna1  c2  c3
0         1 NaN NaN
1         3 NaN NaN
2         5 NaN NaN
3         7 NaN NaN
4         9 NaN NaN
5        11 NaN NaN
6        13 NaN NaN
7        15 NaN NaN

In [221]:
dataframeconvacios.dropna()

Empty DataFrame
Columns: [Columna1, c2, c3]
Index: []

In [222]:
dataframeconvacios.fillna(1)

Columna1  c2  c3
0         1   1   1
1         3   1   1
2         5   1   1
3         7   1   1
4         9   1   1
5        11   1   1
6        13   1   1
7        15   1   1

In [223]:
dataframe1

Columna1  Columna2  Columna3  Columna4  c6
0         1         2         1         0   5
1         3         6         1         1   5
2         5        10         1         2   5
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5

In [224]:
dataframe1["Columna2"]

0     2
1     6
2    10
3    14
4    18
5    22
6    26
7    30
Name: Columna2, dtype: int64

In [225]:
dataframe1.ix[1]

Columna1    3
Columna2    6
Columna3    1
Columna4    1
c6          5
Name: 1, dtype: int64

In [226]:
serie1 = dataframe1["Columna2"]

In [227]:
serie1

0     2
1     6
2    10
3    14
4    18
5    22
6    26
7    30
Name: Columna2, dtype: int64

In [228]:
serie1 > 10

0    False
1    False
2    False
3     True
4     True
5     True
6     True
7     True
Name: Columna2, dtype: bool

In [229]:
dataframe1["Columna2"] > 10

0    False
1    False
2    False
3     True
4     True
5     True
6     True
7     True
Name: Columna2, dtype: bool

In [230]:
dataframe1[dataframe1["Columna2"] > 10]

Columna1  Columna2  Columna3  Columna4  c6
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5

In [231]:
seriecondicion = (dataframe1["Columna2"] > 10) & (dataframe1["Columna4"] > 5)

In [232]:
dataframe1[seriecondicion]

Columna1  Columna2  Columna3  Columna4  c6
6        13        26         1         6   5
7        15        30         1         7   5

In [233]:
dataframe1[seriecondicion]["Columna2"]

6    26
7    30
Name: Columna2, dtype: int64

In [234]:
dataframe1

Columna1  Columna2  Columna3  Columna4  c6
0         1         2         1         0   5
1         3         6         1         1   5
2         5        10         1         2   5
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5

In [235]:
dataframe1["Columna1"]

0     1
1     3
2     5
3     7
4     9
5    11
6    13
7    15
Name: Columna1, dtype: int64

In [236]:
data2=dataframe1[dataframe1["Columna1"]>5]

In [237]:
data2

Columna1  Columna2  Columna3  Columna4  c6
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5

# Apply

In [238]:
dataframe1

Columna1  Columna2  Columna3  Columna4  c6
0         1         2         1         0   5
1         3         6         1         1   5
2         5        10         1         2   5
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5

In [239]:
def suma(val):
    return val+1

In [240]:
suma(3)

4

In [241]:
dataframe1.applymap(suma)

Columna1  Columna2  Columna3  Columna4  c6
0         2         3         2         1   6
1         4         7         2         2   6
2         6        11         2         3   6
3         8        15         2         4   6
4        10        19         2         5   6
5        12        23         2         6   6
6        14        27         2         7   6
7        16        31         2         8   6

In [242]:
dataframe1.applymap(lambda element : 2*element+1)

Columna1  Columna2  Columna3  Columna4  c6
0         3         5         3         1  11
1         7        13         3         3  11
2        11        21         3         5  11
3        15        29         3         7  11
4        19        37         3         9  11
5        23        45         3        11  11
6        27        53         3        13  11
7        31        61         3        15  11

In [243]:
dataframe1.apply(lambda serie: 2*serie)

Columna1  Columna2  Columna3  Columna4  c6
0         2         4         2         0  10
1         6        12         2         2  10
2        10        20         2         4  10
3        14        28         2         6  10
4        18        36         2         8  10
5        22        44         2        10  10
6        26        52         2        12  10
7        30        60         2        14  10

In [244]:
dataframe1.apply(lambda serie: serie.max())

Columna1    15
Columna2    30
Columna3     1
Columna4     7
c6           5
dtype: int64

In [245]:
dataframe1.apply(lambda serie: Series([serie.min(),serie.max()]))

Columna1  Columna2  Columna3  Columna4  c6
0         1         2         1         0   5
1        15        30         1         7   5

In [246]:
dataframe1.apply(lambda serie: Series([serie[0],serie[1]]))

Columna1  Columna2  Columna3  Columna4  c6
0         1         2         1         0   5
1         3         6         1         1   5

In [247]:
dataframe1


Columna1  Columna2  Columna3  Columna4  c6
0         1         2         1         0   5
1         3         6         1         1   5
2         5        10         1         2   5
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5

In [248]:
dataframe1["Columna1"].min()

1

In [249]:
def minserie(serie):
    return serie.sum()

In [250]:
minserie(dataframe1["Columna2"])

128

In [251]:
dataframe1.apply(minserie)

Columna1     64
Columna2    128
Columna3      8
Columna4     28
c6           40
dtype: int64

In [252]:
def ask(row):
    return row["capacity"]*row["km"]

In [253]:
paxdata = DataFrame({'vuelo':["AF101","AF102"],
                     'capacity':[70,100],
                     'km':[10000,1000]
    })

In [254]:
paxdata

capacity     km  vuelo
0        70  10000  AF101
1       100   1000  AF102

In [255]:
paxdata["ask"] = paxdata.apply(ask,axis=1)

In [256]:
paxdata

capacity     km  vuelo     ask
0        70  10000  AF101  700000
1       100   1000  AF102  100000

## Loading and saving data

In [257]:
import pandas as pd
from pandas import Series,DataFrame

In [258]:
!ls -l /media/sf_Documents/data/opentraveldata/optd_aircraft.csv

-rwxrwx--- 1 root vboxsf 18612 nov  8 13:54 /media/sf_Documents/data/opentraveldata/optd_aircraft.csv


In [259]:
aircraftdf = pd.read_csv("/media/sf_Documents/data/opentraveldata/optd_aircraft.csv",sep="^")

In [260]:
aircraftdf.head()

iata_code manufacturer                          model iata_group  \
0       100       Fokker                            100        100   
1       141          BAe                        146-100        146   
2       142          BAe  BAE Systems 146-200 Passenger        146   
3       143          BAe                        146-300        146   
4       146          BAe                            146        NaN   

  iata_category icao_code  nb_engines aircraft_type  
0            2J      F100           2             J  
1            4J      B461           4             J  
2            4J      B462           4             J  
3            4J      B463           4             J  
4           NaN       NaN         NaN           NaN

In [261]:
len(aircraftdf)

457

In [262]:
aircraftdf.describe()

nb_engines
count  343.000000
mean     2.408163
std      0.842679
min      1.000000
25%      2.000000
50%      2.000000
75%      3.000000
max      6.000000

In [263]:
aircraftdf.columns

Index([u'iata_code', u'manufacturer', u'model', u'iata_group',
       u'iata_category', u'icao_code', u'nb_engines', u'aircraft_type'],
      dtype='object')

In [264]:
aircraftdf.rank()

iata_code  manufacturer  model  iata_group  iata_category  icao_code  \
0            1         336.5    2.0         2.0           92.5      254.0   
1            2          89.0    9.0         4.0          307.0       94.5   
2            3          89.0  201.0         4.0          307.0       96.5   
3            4          89.0   10.0         4.0          307.0       98.5   
4            5          89.0    4.0         NaN            NaN        NaN   
5            6          89.0    5.0         NaN            NaN        NaN   
6            7          89.0    6.0         7.0          307.0       94.5   
7            8          89.0    7.0         7.0          307.0       96.5   
8            9          89.0    8.0         7.0          307.0       98.5   
9           10          33.5  142.5         NaN            NaN        NaN   
10          11          33.5  134.0         NaN            NaN        NaN   
11          12          33.5  135.0         9.5           92.5       49.5   
12          13          33.5  137.0         9.5           92.5       49.5   
13          14          33.5  140.0        16.5           92.5       52.0   
14          15          33.5  142.5        16.5           92.5       53.0   
15          16          33.5  139.0         NaN            NaN        NaN   
16          17          33.5  144.0         NaN            NaN        NaN   
17          18          33.5  136.0        11.5           92.5       49.5   
18          19          33.5  138.0        11.5           92.5       49.5   
19          20          33.5  148.0        16.5           92.5       55.0   
20          21          33.5  151.0        16.5           92.5       58.0   
21          22          33.5  146.0        16.5           92.5       55.0   
22          23          33.5  149.0        16.5           92.5       58.0   
23          24          33.5  141.0         NaN            NaN        NaN   
24          25          33.5  145.0         NaN            NaN        NaN   
25          26          33.5  147.0        13.0           92.5       55.0   
26          27          33.5  150.0        20.0           92.5       58.0   
27          28          33.5  152.0         NaN            NaN        NaN   
28          29          33.5  154.0        21.5           92.5       60.5   
29          30          33.5  156.0        21.5           92.5       62.0   
..         ...           ...    ...         ...            ...        ...   
427        428         433.0  423.0       339.0          350.5      331.0   
428        429         424.5  434.0       340.5          221.5      335.0   
429        430         424.5  435.0       340.5          221.5      335.0   
430        431         424.5  433.0       342.0          221.5      335.0   
431        432         429.5  430.0       343.0          221.5      337.0   
432        433         429.5  431.0       344.0          221.5      338.0   
433        434         429.5  428.0         NaN            NaN        NaN   
434        435         429.5  429.0       345.0          221.5      333.0   
435        436           8.5  248.0         NaN            NaN        NaN   
436        437         437.0  437.0         NaN            NaN        NaN   
437        438         437.0  438.0       346.5           92.5      357.5   
438        439         437.0  439.0       346.5           92.5      339.0   
439        440         330.5  424.0       348.0          221.5       15.0   
440        441         330.5  425.0       349.0          221.5       15.0   
441        442         427.0  452.0       350.0          339.5       72.5   
442        443         445.0  446.0       351.0           92.5      342.5   
443        444         445.0  447.0       352.0           92.5      342.5   
444        445         445.0  448.0       353.0           92.5      344.0   
445        446         247.0  442.0       354.0           11.5      345.0   
446        447         440.5  443.0       355.0          359.5       33.0   
4

In [265]:
dataframe1

Columna1  Columna2  Columna3  Columna4  c6
0         1         2         1         0   5
1         3         6         1         1   5
2         5        10         1         2   5
3         7        14         1         3   5
4         9        18         1         4   5
5        11        22         1         5   5
6        13        26         1         6   5
7        15        30         1         7   5

In [266]:
dataframe1.rank(method="first",ascending=False)

Columna1  Columna2  Columna3  Columna4  c6
0         8         8         1         8   1
1         7         7         2         7   2
2         6         6         3         6   3
3         5         5         4         5   4
4         4         4         5         4   5
5         3         3         6         3   6
6         2         2         7         2   7
7         1         1         8         1   8

In [267]:
aircraftdf.sum()

nb_engines    826
dtype: float64

In [268]:
aircraftdf.head()

iata_code manufacturer                          model iata_group  \
0       100       Fokker                            100        100   
1       141          BAe                        146-100        146   
2       142          BAe  BAE Systems 146-200 Passenger        146   
3       143          BAe                        146-300        146   
4       146          BAe                            146        NaN   

  iata_category icao_code  nb_engines aircraft_type  
0            2J      F100           2             J  
1            4J      B461           4             J  
2            4J      B462           4             J  
3            4J      B463           4             J  
4           NaN       NaN         NaN           NaN

In [269]:
aircraftdf.to_csv("salida.csv")

In [270]:
!ls -l salida.csv

-rw-rw-r-- 1 sebas sebas 21017 dic 16 18:29 salida.csv


In [271]:
pwd

u'/home/sebas/dev/projects/pandasclass'

In [272]:
aircraftdf.to_excel("salida.xls")

In [273]:
minidf = aircraftdf.head()

In [274]:
minidf.to_dict(orient="records")

[{'aircraft_type': 'J',
  'iata_category': '2J',
  'iata_code': '100',
  'iata_group': '100',
  'icao_code': 'F100',
  'manufacturer': 'Fokker',
  'model': '100',
  'nb_engines': 2.0},
 {'aircraft_type': 'J',
  'iata_category': '4J',
  'iata_code': '141',
  'iata_group': '146',
  'icao_code': 'B461',
  'manufacturer': 'BAe',
  'model': '146-100',
  'nb_engines': 4.0},
 {'aircraft_type': 'J',
  'iata_category': '4J',
  'iata_code': '142',
  'iata_group': '146',
  'icao_code': 'B462',
  'manufacturer': 'BAe',
  'model': 'BAE Systems 146-200 Passenger',
  'nb_engines': 4.0},
 {'aircraft_type': 'J',
  'iata_category': '4J',
  'iata_code': '143',
  'iata_group': '146',
  'icao_code': 'B463',
  'manufacturer': 'BAe',
  'model': '146-300',
  'nb_engines': 4.0},
 {'aircraft_type': nan,
  'iata_category': nan,
  'iata_code': '146',
  'iata_group': nan,
  'icao_code': nan,
  'manufacturer': 'BAe',
  'model': '146',
  'nb_engines': nan}]

In [275]:
minidf.to_json(orient="records")

'[{"iata_code":"100","manufacturer":"Fokker","model":"100","iata_group":"100","iata_category":"2J","icao_code":"F100","nb_engines":2.0,"aircraft_type":"J"},{"iata_code":"141","manufacturer":"BAe","model":"146-100","iata_group":"146","iata_category":"4J","icao_code":"B461","nb_engines":4.0,"aircraft_type":"J"},{"iata_code":"142","manufacturer":"BAe","model":"BAE Systems 146-200 Passenger","iata_group":"146","iata_category":"4J","icao_code":"B462","nb_engines":4.0,"aircraft_type":"J"},{"iata_code":"143","manufacturer":"BAe","model":"146-300","iata_group":"146","iata_category":"4J","icao_code":"B463","nb_engines":4.0,"aircraft_type":"J"},{"iata_code":"146","manufacturer":"BAe","model":"146","iata_group":null,"iata_category":null,"icao_code":null,"nb_engines":null,"aircraft_type":null}]'

In [276]:
fileoutput = open("fichero.json","w")
fileoutput.write(minidf.to_json(orient="records"))
fileoutput.close()

In [277]:
!ls -l fichero.json

-rw-rw-r-- 1 sebas sebas 792 dic 16 18:29 fichero.json


In [278]:
aircraftdf2 = pd.read_excel("salida.xls")

In [279]:
aircraftdf2.head()

iata_code manufacturer                          model iata_group  \
0       100       Fokker                            100        100   
1       141          BAe                        146-100        146   
2       142          BAe  BAE Systems 146-200 Passenger        146   
3       143          BAe                        146-300        146   
4       146          BAe                            146        NaN   

  iata_category icao_code  nb_engines aircraft_type  
0            2J      F100           2             J  
1            4J      B461           4             J  
2            4J      B462           4             J  
3            4J      B463           4             J  
4           NaN       NaN         NaN           NaN

# Fake Data Creation

In [280]:
fake = DataFrame({'col1':range(0,1000)})

In [281]:
fake.head()

col1
0     0
1     1
2     2
3     3
4     4

In [282]:
random = DataFrame(np.random.randn(1000,1))

In [283]:
random.head()

0
0  0.658404
1 -1.876418
2 -0.521115
3 -1.457490
4  2.284291

In [284]:
100*random

0
0     65.840382
1   -187.641765
2    -52.111539
3   -145.748978
4    228.429096
5     36.706874
6   -185.356965
7    113.227315
8    -21.091020
9     35.659360
10     5.431550
11   105.101871
12  -119.259304
13    -3.394435
14   -25.456403
15    81.834280
16  -177.832794
17    34.119094
18   -64.315732
19   -42.847868
20  -199.309909
21    84.988902
22   122.728765
23    54.682882
24   -14.131208
25   182.150484
26    64.596318
27   190.030053
28    24.679714
29   -19.810632
..          ...
970  144.803273
971  122.583210
972   16.330498
973 -183.000839
974  -50.565152
975 -111.296888
976  -93.350188
977 -147.745100
978 -176.568107
979 -176.398760
980   28.935447
981   59.718445
982   20.147697
983  -73.351610
984   18.359012
985  -55.481606
986   42.349905
987 -190.346121
988 -127.180035
989  -21.953026
990  -85.592253
991 -100.015637
992   -8.615271
993  -36.869539
994  133.628707
995  127.551411
996  231.676413
997  -80.823248
998  159.701736
999  103.359116

[1000 rows x 1 columns]

In [285]:
random.columns = ['Population']

In [286]:
random.head()

Population
0    0.658404
1   -1.876418
2   -0.521115
3   -1.457490
4    2.284291

In [287]:
len(random)

1000

In [288]:
random["Population"]=random.apply(lambda row: int(abs(100*row[0])), axis=1)

In [289]:
random.head()

Population
0          65
1         187
2          52
3         145
4         228