# Playing with numPy
## Visit https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
### import numpy, see the version

In [2]:
import numpy as np
np.version.version

'1.9.2'

## First steps: creating vectors and matrices: 'ndarrys'. 
### create ndarrays from a list, from list of list. See dim, shape, reshape.

In [10]:
list = [1,2,3,4]

In [98]:
a = np.array(list)
print a.ndim
print a.shape
a.reshape(2,2)

1
(4,)


array([[1, 2],
       [3, 4]])

### special ndarrays: zeros, ones, ones_like, eye, empty.

In [96]:
b = np.zeros((3,4))

In [15]:
c = np.ones((4,5))

In [17]:
d = np.ones_like(b)

In [38]:
e = np.eye(5,k=-1)
print e

[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]]


In [22]:
f = np.empty ((4,5),dtype = int)

In [33]:
f

array([[    140624673197080,            38957664,                   0,
                          0,        468151435264],
       [7236833184642769531, 7881144752318672485, 7310875413622977637,
        7308895138223563308, 3905013837197359650],
       [7221014260803265125, 4123095169718629421, 7076387812872632376,
        2477601244162897208, 8319683848551211564],
       [2462380941086177826, 2478217245770216563, 3543546967188709946,
        4193751015229500722, 3472607593673406515]])

### arange and random

In [133]:
a2 = np.arange(1,13).reshape(4,3)
print a2
g = np.arange(15)
print g
print g.ndim
print g.shape
g.shape=(5,3)
print "\n"
print g
print "\n"
np.reshape(g,(5,3))#!!!!
g.reshape(5,3)#!!!!
g = g.reshape(5,3)
print g
print g.ndim
print g.shape
print np.arange(8,-5,-1)
print np.random.random((2,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
1
(15,)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
2
(5, 3)
[ 8  7  6  5  4  3  2  1  0 -1 -2 -3 -4]
[[ 0.45110421  0.0026362   0.39429383]
 [ 0.7927826   0.65791424  0.68784231]]


## Indexing and slicing
### (1) Acessing narrays

In [59]:
print g[0,2]
print g[1]

2
[3 4 5]


### (2) Slicing

In [86]:
print g[0:3]
print "\n"
print g[1:]
print "\n"
print g[:3]
print "\n"
print g[0:4,1:3]
print "\n"
print g[0:5,0:4:2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]
 [12 14]]


In [123]:
a2==3
print a2[a2==3]
print a2[a2>3]
print a2[a2%2==0]

[3]
[ 4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


### (3) Copying: careful!!

In [117]:
a2 = np.arange(1,13).reshape(4,3)
b = a2[1]
b[1]=-1
print a2
b[:]=3
c=a2[1].copy()
c
c[:]=[1,-3,0]
print c
print a2

[[ 1  2  3]
 [ 4 -1  6]
 [ 7  8  9]
 [10 11 12]]
[ 1 -3  0]
[[ 1  2  3]
 [ 3  3  3]
 [ 7  8  9]
 [10 11 12]]


## Basic operations
### (1) Element wise operations

In [125]:
print a
a*a

[1 2 3 4]


array([ 1,  4,  9, 16])

In [126]:
a**a

array([  1,   4,  27, 256])

In [127]:
a.dot(a)

30

In [128]:
a+2

array([3, 4, 5, 6])

In [129]:
1/a2

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### (2) Operations on matrixes: dot, transpose, sum, cumsum, cumprod...

In [134]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [136]:
a2.dot(np.arange(3))

array([ 8, 17, 26, 35])

In [138]:
a2.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [152]:
a2.transpose((1,0))#!!!!!

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [163]:
print a2.sum()
print a2.sum(0)
print a2.sum(1)
print a2.cumsum()
print a2.cumsum(0)
print a2.cumsum(1)
print a2.cumprod()
print a2.cumprod(0)
print a2.cumprod(1)

78
[22 26 30]
[ 6 15 24 33]
[ 1  3  6 10 15 21 28 36 45 55 66 78]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]
 [22 26 30]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]
 [10 21 33]]
[        1         2         6        24       120       720      5040
     40320    362880   3628800  39916800 479001600]
[[   1    2    3]
 [   4   10   18]
 [  28   80  162]
 [ 280  880 1944]]
[[   1    2    6]
 [   4   20  120]
 [   7   56  504]
 [  10  110 1320]]


## numPy ndarrays versus matrix

## Linear Algebra
### See http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html

In [164]:
from numpy import linalg as la

In [165]:
help(la)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

FILE
    /usr/lib64/python2.7/site-packages/numpy/linalg/__init__.py

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decompo

### Trace, determinant and inverse

In [180]:
print a2
print a2.trace()
print a2.trace(1)
print a2.trace(-1)
print la.det(a2[0:3])
print la.inv(a2[0:3])
print la.inv(a2[0:3]).dot(a2[0:3])
print np.dot(la.inv(a2[0:3]),a2[0:3])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
15
8
24
6.66133814775e-16
[[ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]
 [  9.00719925e+15  -1.80143985e+16   9.00719925e+15]
 [ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]]
[[ 0. -4. -8.]
 [-8.  0.  0.]
 [ 4.  0.  0.]]
[[ 0. -4. -8.]
 [-8.  0.  0.]
 [ 4.  0.  0.]]


### Norm of a vector and a matrix

In [181]:
help(la.norm)

Help on function norm in module numpy.linalg.linalg:

norm(x, ord=None, axis=None)
    Matrix or vector norm.
    
    This function is able to return one of seven different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D.
    ord : {non-zero int, inf, -inf, 'fro'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object.
    axis : {int, 2-tuple of ints, None}, optional
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these matrices
        are computed.  If `axis` is None then either a vector norm (when `x`
        is 1-D) or a matrix norm (when `x` is 2-D) is returned.
    

### Matrix factorization: eigen-decomposition y SVD

### Comparison with python: execution times 

In [182]:
import time
size_of_vec = 1000
def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1
def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

In [186]:
t1 = pure_python_version()
t2 = numpy_version()
print t1
print t2
print(t1/t2)

0.000154972076416
2.78949737549e-05
5.55555555556
